### ISSUE TITLE
More interfaces about ZigBee ?

### ISSUE THREAD

**Issue by wenboo** [SamsungARTIK/artik-sdk#11]
Hello Dears,

We've seen the ZigBee interfaces such as network leave / network join etc. from

https://github.com/SamsungARTIK/artik-sdk/blob/master/src/zigbee.js

Are there any more interfaces for functions just like ZigBee Role Change / Muticast / Unicast and so on ?

Thank you.

**Comment by glemercier** [comment]
Hi,

We are currently working on improving this API, with more roles and features to be expected. Stay tuned for next releases to come.

Thanks,

Greg

**Comment by wenboo** [comment]
Expected. Thanks for all your contributions. 

wenboo

**Comment by glemercier** [comment]
Hi Wenboo,

We just released version 1.2.0 of the SDK, along with node.js module 1.2.1. It contains more Zigbee profiles already implemented, refer to this [example](https://github.com/SamsungARTIK/artik-sdk/blob/master/examples/zigbee-example.js) for details.
