### ISSUE TITLE
artik-sdk requires libartik-sdk-mqtt

### ISSUE THREAD

**Issue by sshtel** [SamsungARTIK/artik-sdk#12]
I am testing nodejs app in artik-sdk/examples but it requires libartik-sdk-mqtt even though sample code does not necessarily use mqtt.

Maybe artik-sdk node library is referring mqtt.

when I tried to install libartik-sdk-mqtt, I saw this

`No package libartik-sdk-mqtt available.`

When can I get the mqtt library?

see below:

`[root@artik examples]# node serial-example.js
module.js:434
return process.dlopen(module, path._makeLong(filename));
^

Error: libartik-sdk-mqtt.so.1: cannot open shared object file: No such file or directory
at Error (native)
at Object.Module._extensions..node (module.js:434:18)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/root/workspace/awair-v2-platform/artik-sdk/examples/serial-example.js:1:77)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)`

**Comment by sshtel** [comment]
I could run example code at 1.0.3 version but not available from 1.1.1 due to mqtt lib dependency

**Comment by wenboo** [comment]
@sshtel  Hi ~ which artik board have u used and what's the Federa version ? 

>[root@localhost etc]# cat /etc/issue

Thanks

**Comment by glemercier** [comment]
MQTT is not available in the current SDK v1.0.2, for which you should checkout the "1.0-maintenance" branch (or just use "npm install artik-sdk). MQTT will be available in the next version of the SDK v1.1 to be released soon.

**Comment by glemercier** [comment]
MQTT is now available in new release 1.1.3 of the SDK. Do the following on your ARTIK board to update to this new version:

`
$ dnf makecache --refresh
$ dnf update
`
Update the node.js addon:
`$ npm install artik-sdk`
