### ISSUE TITLE
Is I2C API changed?

### ISSUE THREAD

**Issue by sshtel** [SamsungARTIK/artik-sdk#13]
I2C API
the number of parameters of write_register() is 2 according to Document.(README)

But sample code seems likely pass 3 which means address, buffer and size.

**Comment by glemercier** [comment]
This is a discrepancy in the I2C sample code, only 2 parameters are required by the API (address, buffer). It is harmless since the 3rd parameter is ignored by the API, but we'll fix it for purpose of clarity.

Thanks for the report.

**Comment by glemercier** [comment]
Discrepancy was fixed and released in new version 1.1.3. Closing ticket.
