### ISSUE TITLE
Error: /lib/artik-sdk.node: undefined symbol: node_module_register

### ISSUE THREAD

**Issue by JayeshLunkad** [SamsungARTIK/artik-sdk#15]
Hi ,
I was trying sample nodejs example. I have created node js project and while running one of the script 
it gives following error:

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /root/projects/NodeJS/Nodejs/lib/artik-sdk.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object. (/root/projects/NodeJS/Nodejs/test/media-test.js:1:77)
    at Module._compile (module.js:456:26)

Thanks ,
Jayesh

**Comment by artik-iot** [comment]
Hi Jayesh,

I'm not sure you use this module correctly. Here is what you need to use it.

- An ARTIK board (520/530/710/1020) with Fedora 24 installed
- node.js<http://node.js>  4.7 => dnf install nodejs
- ARTIK SDK 1.1.3 => dnf install libartik-sdk-tests

Then you can install the node.js<http://node.js> module as a dependency of your own JS program by doing: "npm install artik-sdk"

This github repo is used for source reference but it's not recommended to use the module from cloning the git repo, "npm" installation is better to handle the dependencies.

Greg

-------- Message original --------
De : JayeshLunkad <notifications@github.com<mailto:notifications@github.com>>
Date : ven. 24 mars 2017 07:14
À : SamsungARTIK/artik-sdk <artik-sdk@noreply.github.com<mailto:artik-sdk@noreply.github.com>>
CC : Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Objet : [SamsungARTIK/artik-sdk] Error: /lib/artik-sdk.node<http://artik-sdk.node>: undefined symbol: node_module_register (#15)

Hi ,
I was trying sample nodejs example. I have created node js project and while running one of the script
it gives following error:

module.js:356
Module._extensions[extension](this, filename);
^
Error: /root/projects/NodeJS/Nodejs/lib/artik-sdk.node: undefined symbol: node_module_register
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/root/projects/NodeJS/Nodejs/test/media-test.js:1:77)
at Module._compile (module.js:456:26)

Thanks ,
Jayesh

**Comment by JayeshLunkad** [comment]
Hi Greg,
Thanks for your response 
I Have done all the steps :
**- An ARTIK board (520/530/710/1020) with Fedora 24 installed
- node.js<http://node.js>  4.7 => dnf install nodejs
- ARTIK SDK 1.1.3 => dnf install libartik-sdk-tests**

**Node Version:**
[root@localhost ~]# node --version
v0.10.42 

**ARTIK SDK version** :
[root@localhost ~]# npm list -g
npm WARN unmet dependency /lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
 -> /usr/lib /lib
├── abbrev@1.0.4
├── ansi@0.2.1
├── archy@0.0.2
├── artik-sdk@1.1.3



Can  you please help where i am going wrong

Thanks,
Jayesh

**Comment by glemercier** [comment]
The issue is that you have node.js 0.10 installed, only 4.7 is supported by this module.

Can you check your fedora version:
`
$ cat /etc/redhat-release
$ cat /etc/artik_release
`
Also you can try `dnf update` to make sure your are up-to-date with Fedora's repo

**Comment by JayeshLunkad** [comment]
[root@localhost ~]# cat /etc/redhat-release
Fedora release 22 (Twenty Two)

[root@localhost ~]# cat /etc/artik_release
RELEASE_VERSION=0520GC0F-3AF-01Q2
RELEASE_DATE=20160415.224028
RELEASE_UBOOT=U-Boot 2012.07
RELEASE_KERNEL=3.10.93


I have downgraded node js version but i am unable to get 4.7 downloaded

**Comment by glemercier** [comment]
Actually node.js 4.7 is a newer release than 0.10. The reason why you don't get 4.7 is because you are running Fedora 22 which does not support this newer version of node.js. You should upgrade your system image to Fedora 24 (ARTIK 520 Firmware Image A520-OS-2.0.0), available for download here: http://developer.artik.io/downloads/ef3c9bd2-2081-4558-8ca9-b7de000b0558/download

**Comment by JayeshLunkad** [comment]
Thanks greg for your quick response and the reference for firmware.
is there any documentation to update the firmware of artik ?

**Comment by artik-iot** [comment]
There you go: developer.artik.io/documentation/developer-guide/update-image/updating-artik-image.html<http://developer.artik.io/documentation/developer-guide/update-image/updating-artik-image.html>

-------- Message original --------
De : JayeshLunkad <notifications@github.com<mailto:notifications@github.com>>
Date : ven. 24 mars 2017 12:59
À : SamsungARTIK/artik-sdk <artik-sdk@noreply.github.com<mailto:artik-sdk@noreply.github.com>>
CC : Gregory Lemercier <g.lemercier@samsung.com<mailto:g.lemercier@samsung.com>>,Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Objet : Re: [SamsungARTIK/artik-sdk] Error: /lib/artik-sdk.node<http://artik-sdk.node>: undefined symbol: node_module_register (#15)

Thanks greg for your quick response and the reference for firmware.
is there any documentation to update the firmware of artik ?
