### ISSUE TITLE
cloud-websocket-example.js

### ISSUE THREAD

**Issue by hwilyric** [SamsungARTIK/artik-sdk#19]
I’m studying a websocket protocol and found an example named cloud-websocket-example.js.
The weird thing I found was that when websocket connection is created accroding to function named websocket_open_stream, It doesn’t have URI as a parameter.
How can we know where the client connects?

**Comment by glemercier** [comment]
This example uses the ARTIK Cloud dedicated websocket AP in the "cloud" module. Therefore all the ARTIK Cloud specific information (URL, port, etc...) is abstracted and you just need to provide your ARTIK Cloud device ID and token.

If you don't want to connect to ARTIK Cloud but to some other websocket server, you can use the generic websocket API from the "websocket" module (documentation [here](https://github.com/SamsungARTIK/artik-sdk/blob/master/doc/WEBSOCKET_README.md)). For this latter case, you also have an [example](https://github.com/SamsungARTIK/artik-sdk/blob/master/examples/websocket-example.js)  that shows how to connect to a public "echo" test webserver.

**Comment by hwilyric** [comment]
Thanks for quick response. I recognized that It was already defined in artik-sdk module as you said :)
