### ISSUE TITLE
lib/arik-sdk.node

### ISSUE THREAD

**Issue by hwilyric** [SamsungARTIK/artik-sdk#20]
Most of examples used artik-sdk.node.
In order to fully understadn the examples, I thought I need to read that file.
However It's encoded so that I was not able to read it.
Is it on purpose? or going to open to public later?

**Comment by glemercier** [comment]
"artik-sdk.node" is a binary addon that wraps the C/C++ APIs of the [ARTIK SDK](https://developer.artik.io/documentation/api/index.html). Right now it's only available for Samsung ARTIK boards running the Fedora 24 distribution, if you don't have one of these then I'm afraid you are looking at the wrong project for you :-)
