### ISSUE TITLE
lwm2m-example.js

### ISSUE THREAD

**Issue by hwilyric** [SamsungARTIK/artik-sdk#21]
In this example, device will connect to coaps://coaps-api.artik.cloud:5686 where we can send and receiv object/resource value according to https://developer.artik.io/forums/t/coap-example-lwm2m-example-js/3443/2.

What I would like to do is using 5684 port to get messages and actions using CoAP.
I tried to use API which in defined here https://github.com/SamsungARTIK/artik-sdk/blob/HEAD/doc/LWM2M_README.md, But since I don't know what kind of parameters needed when connected to 5686 port, I kept getting errors.

Are you planning to make CoAP example? Or how could I make an example?

**Comment by glemercier** [comment]
LWM2M is a device management layer on top of CoAP, but the ARTIK Cloud CoAP endpoint you are targeting for sending messages and receiving actions is just plain CoAP, therefore the LWM2M library will be no use for that.

The ARTIK SDK does not have a plain CoAP module yet, therefore you'll have to find that somewhere else. With the help of the ARTIK SDK, you can still use REST (messages only), MQTT, or Websocket to do what you are trying to achieve.
