### ISSUE TITLE
npm install isn't working

### ISSUE THREAD

**Issue by nerdrun** [SamsungARTIK/artik-sdk#22]
I would like to install artik-sdk on my artik 710 board.
I'd tried to install but it didn't work
Also I'd tried to do it with my iMac. (Of course it had been connecting Internet).
Same problems.

npm said It is the most likely not a problem with npm itself.

**Comment by glemercier** [comment]
Can you provide more information on what is failing on your ARTIK 710 board? If it's your Wifi connection not working, please refer to https://developer.artik.io/documentation/developer-guide/ethernet-wifi/wifi.html

It's expected that it's not working on your Mac. Installing the artik-sdk module requires building some library that requires ARTIK specific libraries on the target.

**Comment by nerdrun** [comment]
@glemercier Thanks for replying to me. I've installed other npm plugins via artik 710 model. But not worked only artik-sdk. It was written on terminal exactly what I've mentioned. not else.
And of course I've configured wifi following the reference.
I guess I might not to update artik 710 linux version or something.

Thanks. I will try it more.
