### ISSUE TITLE
Problem with using SPI and feedback/question on the implementation

### ISSUE THREAD

**Issue by ksachdeva** [SamsungARTIK/artik-sdk#23]
When I run https://github.com/SamsungARTIK/artik-sdk/blob/1.7-maintenance/test/spi_test/artik_spi_test.c it compiles as well run as expected. This example requires that MOSI and MISO are connected.

I then wanted to send a message from ARTIK 710S to Arduino over SPI and was not able to achieve it using 'artik-sdk'.

After searching for information I came across an article (http://mitchtech.net/raspberry-pi-arduino-spi/) that describes using Raspberry Pi as master and Arduino as slave. The article comes with source code for both platforms.

I was able to follow the article and run it on Raspberry Pi and Arduino as it all work as expected.

##

I then took the same code that ran on Raspberry Pi and only changed the device name from '/dev/spidev0.0' to '/dev/spidev2.0' as on ARTIK 710 the bus number is 2.

I was able to run it successfully and it all work as expected. This confirmed that there is no issue on my side from setup/wiring point of view.

Above also confirmed to me that the SPI implementation on ARTIK 710S (ubuntu) is working properly

The code from the article is directly using the linux ioctl API.

##

I then started to look at the source of artik-sdk and I have some doubts on the implementation.

My understanding is that the user code is supposed to follow following convention/pattern -

request
read/write/read_write
release

The current implementation at https://github.com/SamsungARTIK/artik-sdk/blob/1.7-maintenance/src/modules/systemio/spi/linux_spi.c is opening and closing the file descriptor associated with /dev/spidevx.x multiple times.

For e.g. the method `os_spi_request` opens the file, calls `spi_setup` where various attributes are set and then closes the file.

The methods `os_spi_read`, `os_spi_write` etc also open the file and at the end close it.

I do not have prior expertise in linux device drivers but I would presume that when the file is being closed in `os_spi_request` it is possible that the file may lose the `attributes` that were setup during the `spi_setup` call and hence the potential reason for the behavior I am seeing.

Please suggest 

Regards
Kapil

**Comment by philenotfound** [comment]
Hello Kapil, 

assuming you are using a kernel >= 3.19 the speed attribute may get reset to the max speed of the underlying SPI controller upon closing the file descriptor. Which may also explain why the loopback test is still working.
See http://elixir.free-electrons.com/linux/v3.19/source/drivers/spi/spidev.c#L559

As a workaround you could try to open the device file and keep it open while using the SDK functions to avoid that the reference count reaches zero.

**Comment by glemercier** [comment]
Hi Kapil,

Thanks for the detailed report about the issue. The SPI "language" between two chips can greatly vary depending on the slave's requirements, and the issue you mentioned might be related to the way the Arduino expect the signals to be driven.

Do you have a way to probe the SPI signals with an oscilloscope? If so it would greatly help to see what they look like in the working and non-working cases. On our side we use the SPI module of the ARTIK SDK successfully with some SPI chips (see the KDS63XL sensor for instance), but again slave chips may not behave the same way. We'll look at what you provided in the meantime and see if there is anything obvious we can change to address your issue, while keeping our other uses cases working.

Thanks,

Greg
