### ISSUE TITLE
MQTT test example crashes with Segmentation fault

### ISSUE THREAD

**Issue by mmajb** [SamsungARTIK/artik-sdk#26]
Hi,
I'm trying to test the MQTT connection with a device on the Artik cloud. But the example application artik_mqtt_cloud_test.c crashes when the function artik_request_api_module is invoked for the second time for getting the artik_loop_module after it has already been invoked to get the artik_mqtt_module. Any help will be appreciated. Thanks.

Regards,
Ahsan

**Comment by glemercier** [comment]
Can you provide information on the board you are using, the system image that is running, the ARTIK SDK version, etc...

**Comment by mmajb** [comment]
I'm running the application on an Artik 710 with the latest ubuntu image. The Artik SDK is the latest as I cloned the repository (master branch).

**Comment by mmajb** [comment]
Tested the application on Artik 530s with ubuntu and Artik SDK version 1.8-0. This time the application doesn't crash but also fails to connect to the cloud device. Error code -18 is returned. Any idea what might be the issue? Thanks

Ahsan

**Comment by glemercier** [comment]
Can you provide the parameters you passed to the test program? The syntax should be the following:
`mqtt_cloud_test <ARTIK Cloud device ID> <ARTIK Cloud device token> <JSON formatted message>`

**Comment by mmajb** [comment]
I have tried different formats: with and without quotes. Here is an example:
./mqtt_cloud_test 123456547568573634634 1234323542634636346 "{"data":{"field":"value"}}"

**Comment by glemercier** [comment]
You should try like this:

`./mqtt_cloud_test 123456547568573634634 1234323542634636346 '{"field":"value"}'`

Note that the "data" field in the JSON message is abstracted by the API, therefore you just pass the JSON data of the message. Also make sure the "field" item in your JSON is supported by the manifest of the device type corresponding to the device ID. For instance if you have the standard boolean 'state' field in the manifest, it should look like this:

`./mqtt_cloud_test 123456547568573634634 1234323542634636346 '{"state":true}'`

**Comment by mmajb** [comment]
Tried that as well. Same result. I get the -18 error code.

 ./mqtt_cloud_test c66ba84ad42541be901c0a3feb4e6 e565963c73cf4199cd8fdd8a75079 '{"deviceId":"12345678"}'

The field deviceId is part of the manifest and its value is of string type.

**Comment by glemercier** [comment]
Can you check the date of your device? Is it valid? The MQTT server from ARTIK Cloud uses SSL and does certificate verification. If the date is invalid it may cause the SSL handshake to fail if the date is out of the certificate's validity period.

**Comment by mmajb** [comment]
Date is also correct.

**Comment by glemercier** [comment]
This is probably due to the ARTIK Cloud certificate which changed a few months back, we added a patch after 1.8.0 release to update this certificate in the MQTT test program: https://github.com/SamsungARTIK/artik-sdk/commit/a2140b8ab8e412073ce198deaa812def05a4a826

You may update to the tip of the "1.8-maintenance" branch: https://github.com/SamsungARTIK/artik-sdk/tree/1.8-maintenance

Or cherry-pick single patch: https://github.com/SamsungARTIK/artik-sdk/commit/a2140b8ab8e412073ce198deaa812def05a4a826

**Comment by mmajb** [comment]
Yup. Resolved the issue. Thanks for the help glemercier.
