### ISSUE TITLE
Shutdown of the Samsung ARTIK project

### ISSUE THREAD

**Issue by viktorgino** [SamsungARTIK/artik-sdk#38]
Hi

I know that this isn't possibly the best place to ask this, but I can't find contact details for the ARTIK team and I believe its best to ask this in public.

According to this new article: http://www.businesskorea.co.kr/news/articleView.html?idxno=27384 Samsung is shutting down the ARTIK project. The disappearance of the ARTIK developer forum and the archiving of the TizenRT repository which was maintained by the ARTIK team https://github.com/SamsungARTIK/TizenRT suggests seems to confirm this too.

Is there an official statement on the future of the ARTIK project and what will happen to the management of this project going forward?

Thanks.

**Comment by JunhwanPark** [comment]
Hi @viktorgino 

Because there was no answer for a long time in your question, I write.

You already know because you read the article. ARTIK will no longer be developed. (Simple support will be available for a while.) However, ARTIK's repositories will not disappear. Of course, no further updates are expected, but we do not delete it because it is our record.
I also confirmed that the developer forum is gone. If you have any questions about TizenRT, check out the https://github.com/Samsung/TizenRT repository. TizenRT used in ARTIK was a version that forked it.

I am very thankful for your interest because I was a developer of ARTIK and TizenRT. 
If you have any questions, you may contact me. If I can, I will help.

Bye.

**Comment by viktorgino** [comment]
Hi @JunhwanPark 

Thanks for your response! Appreciate all the work that has gone into this project, its pretty sad to see it go, I think it had a lot of potential.

Thanks for your and your teams hard work on this, good luck with whatever comes next.

**Comment by Guardado** [comment]
I still can't believe it. I was developing two products with the ARTIK modules 😢.  At lest the modules or even the processors used by the modules should continue to be sold by third-party distributors.

**Comment by JunhwanPark** [comment]
Hi @Guardado 
I do not know whether the module is currently sold. However, at least this is what the ARTIK05x used.
https://www.samsung.com/semiconductor/minisite/exynos/products/iot/exynos-i-t200/

**Comment by Guardado** [comment]
Hi @JunhwanPark 
Thank you for your replay.  I think a Corex-M (exynos-i-t200) looks more like a microcontroller and may not have the performance we need. I guess I'm in a niche where we need application processors but also the same capabilities of micro-controllers. As a medium company we don't have the capability of building complex modules, so the ARTIK530 & ARTIK710 where perfect for our products, e.g., our weight scale with linux (http://www.tor-rey-electronics.com/wifi-scales/WLS-40L.php). 
At the same time selling the modules on digi-key/arrow/mouser was excellent for companies based on america, it's just so hard trying to buy samples through other distributors and signing NDAs when you can just buy the samples you need with a click. 

Anyway, I apology for venting my frustration here. 
Have great day!.

**Comment by viktorgino** [comment]
@Guardado my company has developed a product using the ARTIK 053 modules, now we are looking to replace it with https://onion.io and a PIC micro controller, this increases the BOM price slightly, but the Onion modules run OpenWRT which is a huge plus for me.

Not sure what you could replace the 530 and the 710 with, that has the same I/Os and display interfaces.
If you don't want to sign NDAs (which I always find frustrating too, some manufacturers don't even let you look at their product list without it) then maybe try the Raspberry Pi Compute module? The biggest problem with the CM would be the display interface, the Artik modules use DSI and the CM's DSI only works with their official screen, but you still have HDMI and DPI. The lack of analogue ports can be easily solved be a low cost micro / low footprint micro controller.

Good luck with finding an alternate solution!

**Comment by JunhwanPark** [comment]
@viktorgino 
The project uses OpenWRT! If you have a chance, I want to buy that module and test it. Thanks for the good info.
I am not doing anything about IoT now, but I am still interested.

**Comment by viktorgino** [comment]
@JunhwanPark the OnionIoT boards are great and the processors they're based on have publicly available documentation, the only drawback is the lack of analogue interfaces, but can be overcome easily with a cheap micro. Definitely check it out.
